module.exports =
  EmployeeType: require('./employee_type')
  RouteType: require('./route_type')
  Route: require('./route')
  TransportType: require('./transport_type')
  Transport: require('./transport')
  AdvertisingType: require('./advertising_type')
  PropertyType: require('./property_type')
  Property: require('./property')