module.exports =
  NewLevelModal: require('./new_level')
  StartRouteModal: require('./start_route')
  NewAdvertisingModal: require('./new_advertising')
  TransportSelectionModal: require('./transport_selection')
  ProlongAdvertisingModal: require('./prolong_advertising')
  BuyFuelModal: require('./buy_fuel')
  StartFactoryModal: require('./start_factory')
  NewTruckingModal: require('./new_trucking')
